#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
#
# Codegen for the mxfp4_moe aux template instances (sort / quant / sort_scales /
# scatter_reduce). The gemm1/gemm2 themselves run on the FlyDSL port
# (aiter/ops/flydsl/mxfp4_gemm{1,2}*.py); only these shared aux kernels are HIP.
#
# Follows the aiter codegen convention: a single codegen class enumerates
# instance records, fans each out into its own .cu translation unit, and emits a
# string -> function-pointer lookup header.

import argparse
from pathlib import Path

# ── Supported shape tuples ─────────────────────────────────────────────────
# (NE, D_HIDDEN, D_INTER, TOPK)
SHAPES = [
    (385, 7168, 512, 9),  # Kimi-K2.5 TP=4
    (385, 7168, 1024, 9),  # Kimi-K2.5 TP=2 (kimik2_c)
    (257, 7168, 512, 9),  # DSR (dsv3_b)
    (257, 7168, 256, 9),  # DSR D_INTER=256 (dsv3_c)
    (384, 7168, 512, 8),  # Kimi-K2 TP=4, TOPK=8 (kimik2_a)
    (385, 7168, 256, 9),  # Kimi-K2.5 D_INTER=256 (kimik2_b)
    (32, 7168, 2048, 8),  # dsv3_a
    (256, 3072, 1536, 8),  # minimax_a (H=3072)
    (256, 3072, 768, 8),  # minimax_b (H=3072)
    (512, 4096, 256, 10),  # qwen35_397b (H=4096, TOPK=10)
    (48, 7168, 3072, 6),  # dsv4_ep8
    (384, 7168, 1536, 6),  # dsv4_tp2
    (384, 7168, 768, 6),  # dsv4_tp4
    (384, 7168, 512, 6),  # dsv4_tp6 (and dsv4_tp8: INTER 384→512 padded)
    (256, 4096, 256, 6),  # dsv4_lite (H=4096)
    (385, 7168, 1536, 7),  # dsv4 NE=385 TOPK=7 (tp2)
    (385, 7168, 768, 7),  # dsv4 NE=385 TOPK=7 (tp4)
    (385, 7168, 512, 7),  # dsv4 NE=385 TOPK=7 (tp6/tp8)
]


# ── Instance record ────────────────────────────────────────────────────────
class Instance:
    """One codegen'd template instance.

    name      kernelName (the dispatch key + the extern "C" symbol).
    fn_type   the aux_dispatch function-pointer type.
    include   the .cuh that defines the launch<...> template.
    params    extern "C" parameter list (one of the *_PARAMS strings).
    body      the launch<...> call wrapped by the extern "C" function.
    """

    __slots__ = ("name", "fn_type", "include", "params", "body")

    def __init__(self, name, fn_type, include, params, body):
        self.name = name
        self.fn_type = fn_type
        self.include = include
        self.params = params
        self.body = body


AUX_INSTANCE_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by gen_instances.py. Do not edit.

#ifdef __HIP_NO_HALF_CONVERSIONS__
#undef __HIP_NO_HALF_CONVERSIONS__
#endif
#ifdef __HIP_NO_HALF_OPERATORS__
#undef __HIP_NO_HALF_OPERATORS__
#endif

#include <hip/hip_runtime.h>
#include <cstdint>
#include <hip/amd_detail/amd_hip_bf16.h>

{kernel_include}
#include "moe_aux/codegen/mxfp4_moe_aux_dispatch.h"

using namespace aiter::mxfp4_moe::aux_dispatch;

extern "C" void {fn_name}(
    hipStream_t stream,
{params})
{{
{body}
}}
"""

AUX_INC_SORT_QUANT = '#include "moe_aux/moe_sort_quant.cuh"'
AUX_INC_3STAGE = '#include "moe_aux/moe_3stage_sort.cuh"'
AUX_INC_SORT_SCALES = '#include "moe_aux/moe_sort_scales.cuh"'
AUX_INC_SCATTER = '#include "moe_aux/moe_scatter_reduce.cuh"'

AUX_SORT_QUANT_PARAMS = """    int            M,
    const void*    a_input,
    const int32_t* topk_ids,
    const float*   topk_weight,
    int32_t*       sorted_token_ids,
    int32_t*       sorted_expert_ids,
    int32_t*       cumsum,
    int32_t*       reverse_sorted,
    float*         sorted_weights,
    void*          a_quant,
    void*          a_scale,
    int32_t*       m_indices,
    void*          bf16_zero_ptr"""

AUX_3STAGE_PARAMS = """    int            M,
    const int32_t* topk_ids,
    const float*   topk_weight,
    int32_t*       sorted_token_ids,
    int32_t*       sorted_expert_ids,
    int32_t*       cumsum,
    int32_t*       reverse_sorted,
    float*         sorted_weights,
    int32_t*       m_indices,
    int32_t*       block_offsets,
    int32_t*       real_counts"""

AUX_SORT_ONLY_ZI_PARAMS = """    int            M,
    const int32_t* topk_ids,
    const float*   topk_weight,
    int32_t*       sorted_token_ids,
    int32_t*       sorted_expert_ids,
    int32_t*       cumsum,
    int32_t*       reverse_sorted,
    float*         sorted_weights,
    int32_t*       m_indices,
    void*          bf16_zero_ptr,
    void*          bf16_zero_ws_ptr,
    long long      workspace_bytes"""

AUX_SORT_ONLY_PARAMS = """    int            M,
    const int32_t* topk_ids,
    const float*   topk_weight,
    int32_t*       sorted_token_ids,
    int32_t*       sorted_expert_ids,
    int32_t*       cumsum,
    int32_t*       reverse_sorted,
    float*         sorted_weights,
    int32_t*       m_indices"""

AUX_QUANT_PARAMS = """    int            M,
    const void*    a_input,
    void*          a_quant,
    void*          a_scale,
    void*          bf16_zero_ptr"""

AUX_SORT_SCALES_PARAMS = """    int            M,
    int            max_sorted,
    void*          a_scale,
    const int32_t* sorted_token_ids,
    const int32_t* cumsum,
    void*          a_scale_sorted_shuffled"""

AUX_SCATTER_PARAMS = """    int            M,
    const void*    flat_out,
    const int32_t* reverse_sorted,
    const float*   sorted_weights,
    void*          out"""

AUX_SCATTER_Q_PARAMS = """    int            M,
    const void*    flat_out_q,
    const void*    flat_out_scale,
    const int32_t* reverse_sorted,
    const float*   sorted_weights,
    void*          out"""


def _aux_sort_quant_body(ne, topk, mb, h):
    return (
        f"    aiter::mxfp4_moe::moe_sort_quant::launch<\n"
        f"        {ne}, {topk}, {mb}, {h}, kNCtasSort, kThreadsSort>(\n"
        f"            stream, M,\n"
        f"            reinterpret_cast<const __hip_bfloat16*>(a_input),\n"
        f"            topk_ids, topk_weight, sorted_token_ids, sorted_expert_ids,\n"
        f"            cumsum, reverse_sorted, sorted_weights,\n"
        f"            reinterpret_cast<uint8_t*>(a_quant),\n"
        f"            reinterpret_cast<uint8_t*>(a_scale),\n"
        f"            m_indices,\n"
        f"            reinterpret_cast<__hip_bfloat16*>(bf16_zero_ptr));"
    )


def _aux_3stage_body(ne, topk, mb):
    return (
        f"    aiter::mxfp4_moe::moe_3stage_sort::launch<\n"
        f"        {ne}, {topk}, {mb}, kSplitSortCtas, kThreadsSort>(\n"
        f"            stream, M,\n"
        f"            topk_ids, topk_weight, sorted_token_ids, sorted_expert_ids,\n"
        f"            cumsum, reverse_sorted, sorted_weights,\n"
        f"            m_indices, block_offsets, real_counts);"
    )


def _aux_sort_only_zi_body(ne, topk, mb, h):
    return (
        f"    aiter::mxfp4_moe::moe_sort_quant::launch_sort_only_with_zero_init<\n"
        f"        {ne}, {topk}, {mb}, {h}, kInlineQuantZeroInitCtas, kThreadsSort>(\n"
        f"            stream, M,\n"
        f"            topk_ids, topk_weight, sorted_token_ids, sorted_expert_ids,\n"
        f"            cumsum, reverse_sorted, sorted_weights,\n"
        f"            m_indices,\n"
        f"            reinterpret_cast<__hip_bfloat16*>(bf16_zero_ptr),\n"
        f"            bf16_zero_ws_ptr, workspace_bytes);"
    )


def _aux_sort_only_body(ne, topk, mb, h):
    return (
        f"    aiter::mxfp4_moe::moe_sort_quant::launch_sort_only<\n"
        f"        {ne}, {topk}, {mb}, {h}, kThreadsSort>(\n"
        f"            stream, M,\n"
        f"            topk_ids, topk_weight, sorted_token_ids, sorted_expert_ids,\n"
        f"            cumsum, reverse_sorted, sorted_weights,\n"
        f"            m_indices);"
    )


def _aux_quant_body(ne, topk, mb, h):
    return (
        f"    aiter::mxfp4_moe::moe_sort_quant::launch_quant<\n"
        f"        {ne}, {topk}, {mb}, {h}, kNCtasSort, kThreadsSort>(\n"
        f"            stream, M,\n"
        f"            reinterpret_cast<const __hip_bfloat16*>(a_input),\n"
        f"            reinterpret_cast<uint8_t*>(a_quant),\n"
        f"            reinterpret_cast<uint8_t*>(a_scale),\n"
        f"            reinterpret_cast<__hip_bfloat16*>(bf16_zero_ptr));"
    )


def _aux_sort_scales_body(bm, ne, h):
    return (
        f"    aiter::mxfp4_moe::moe_sort_scales::launch<\n"
        f"        {bm}, {ne}, {h}, kBK, kNCtasScales, kThreadsScales>(\n"
        f"            stream, M, max_sorted,\n"
        f"            reinterpret_cast<uint8_t*>(a_scale),\n"
        f"            sorted_token_ids, cumsum,\n"
        f"            reinterpret_cast<uint8_t*>(a_scale_sorted_shuffled));"
    )


def _aux_scatter_body(h, topk, nt):
    return (
        f"    aiter::mxfp4_moe::moe_scatter_reduce::launch<\n"
        f"        {h}, {topk}, kThreadsScatterReduce, kColsPerThread, {str(nt).lower()}>(\n"
        f"            stream, M,\n"
        f"            reinterpret_cast<const __hip_bfloat16*>(flat_out),\n"
        f"            reverse_sorted, sorted_weights,\n"
        f"            reinterpret_cast<__hip_bfloat16*>(out));"
    )


def _aux_scatter_q_body(h, topk, nt):
    return (
        f"    aiter::mxfp4_moe::moe_scatter_reduce::launch_mxfp4<\n"
        f"        {h}, {topk}, kThreadsScatterReduceQ, kColsPerThreadQ, {str(nt).lower()}>(\n"
        f"            stream, M,\n"
        f"            reinterpret_cast<const uint8_t*>(flat_out_q),\n"
        f"            reinterpret_cast<const uint8_t*>(flat_out_scale),\n"
        f"            reverse_sorted, sorted_weights,\n"
        f"            reinterpret_cast<__hip_bfloat16*>(out));"
    )


class mxfp4_moe_aux_codegen:
    def __init__(self, working_path):
        self.working_path = Path(working_path)

    def enumerate_instances(self):
        # sort_quant: MB=32 only
        for ne, h, e, topk in SHAPES:
            for mb in (32,):
                yield Instance(
                    f"aux_sort_quant_NE{ne}_TOPK{topk}_MB{mb}_H{h}",
                    "SortQuantFn",
                    AUX_INC_SORT_QUANT,
                    AUX_SORT_QUANT_PARAMS,
                    _aux_sort_quant_body(ne, topk, mb, h),
                )

        # sort (threestage): MB in {32, 64, 128}
        for ne, h, e, topk in SHAPES:
            for mb in (32, 64, 128):
                yield Instance(
                    f"aux_sort3s_NE{ne}_TOPK{topk}_MB{mb}",
                    "Sort3StageFn",
                    AUX_INC_3STAGE,
                    AUX_3STAGE_PARAMS,
                    _aux_3stage_body(ne, topk, mb),
                )

        # sort (inline_quant + zero_init): MB=16
        for ne, h, e, topk in SHAPES:
            for mb in (16,):
                yield Instance(
                    f"aux_sortzi_NE{ne}_TOPK{topk}_MB{mb}_H{h}",
                    "SortOnlyZiFn",
                    AUX_INC_SORT_QUANT,
                    AUX_SORT_ONLY_ZI_PARAMS,
                    _aux_sort_only_zi_body(ne, topk, mb, h),
                )

        # sort (inline_quant): MB=16
        for ne, h, e, topk in SHAPES:
            for mb in (16,):
                yield Instance(
                    f"aux_sortonly_NE{ne}_TOPK{topk}_MB{mb}_H{h}",
                    "SortOnlyFn",
                    AUX_INC_SORT_QUANT,
                    AUX_SORT_ONLY_PARAMS,
                    _aux_sort_only_body(ne, topk, mb, h),
                )

        # quant: MB in {32, 64, 128}.
        for ne, h, e, topk in SHAPES:
            for mb in (32, 64, 128):
                yield Instance(
                    f"aux_quant_NE{ne}_TOPK{topk}_MB{mb}_H{h}",
                    "QuantFn",
                    AUX_INC_SORT_QUANT,
                    AUX_QUANT_PARAMS,
                    _aux_quant_body(ne, topk, mb, h),
                )

        # sort_scales: BM in {32, 64, 128} (MB=16 callers clamp to BM=32)
        for ne, h in sorted({(ne, h) for ne, h, _e, _topk in SHAPES}):
            for bm in (32, 64, 128):
                yield Instance(
                    f"aux_sortscales_BM{bm}_NE{ne}_H{h}",
                    "SortScalesFn",
                    AUX_INC_SORT_SCALES,
                    AUX_SORT_SCALES_PARAMS,
                    _aux_sort_scales_body(bm, ne, h),
                )

        # scatter_reduce / scatter_reduce_q: keyed by (D_HIDDEN, TOPK, NT) only,
        # so dedup across shapes that share an (h, topk).
        for h, topk in sorted({(h, topk) for _ne, h, _e, topk in SHAPES}):
            for nt in (False, True):
                yield Instance(
                    f"aux_scatter_H{h}_TOPK{topk}_NT{1 if nt else 0}",
                    "ScatterReduceFn",
                    AUX_INC_SCATTER,
                    AUX_SCATTER_PARAMS,
                    _aux_scatter_body(h, topk, nt),
                )
                yield Instance(
                    f"aux_scatterq_H{h}_TOPK{topk}_NT{1 if nt else 0}",
                    "ScatterReduceQFn",
                    AUX_INC_SCATTER,
                    AUX_SCATTER_Q_PARAMS,
                    _aux_scatter_q_body(h, topk, nt),
                )

    def gen_instances(self, instances):
        inst_dir = self.working_path / "instances"
        inst_dir.mkdir(exist_ok=True)
        for inst in instances:
            text = AUX_INSTANCE_HEADER.format(
                kernel_include=inst.include,
                fn_name=inst.name,
                params=inst.params,
                body=inst.body,
            )
            (inst_dir / f"{inst.name}.cu").write_text(text)

    # fn_type -> lookup-table macro name (one table per aux entry).
    _MACRO = {
        "SortQuantFn": "GENERATE_AUX_SORT_QUANT_LOOKUP_TABLE",
        "Sort3StageFn": "GENERATE_AUX_SORT3STAGE_LOOKUP_TABLE",
        "SortOnlyZiFn": "GENERATE_AUX_SORT_ONLY_ZI_LOOKUP_TABLE",
        "SortOnlyFn": "GENERATE_AUX_SORT_ONLY_LOOKUP_TABLE",
        "QuantFn": "GENERATE_AUX_QUANT_LOOKUP_TABLE",
        "SortScalesFn": "GENERATE_AUX_SORT_SCALES_LOOKUP_TABLE",
        "ScatterReduceFn": "GENERATE_AUX_SCATTER_REDUCE_LOOKUP_TABLE",
        "ScatterReduceQFn": "GENERATE_AUX_SCATTER_REDUCE_Q_LOOKUP_TABLE",
    }

    @staticmethod
    def _decl_extern_c(inst):
        return (
            f'extern "C" void {inst.name}(\n'
            f"    hipStream_t stream,\n{inst.params});"
        )

    @staticmethod
    def _emit_map(out, macro, names):
        out.append(f"\n#define {macro}() \\\n")
        out.append("    { \\\n")
        for n in names:
            out.append(f'        {{"{n}", &{n}}}, \\\n')
        out.append("    }\n")

    def gen_lookup(self, instances):
        out = ["""// SPDX-License-Identifier: MIT
// Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by gen_instances.py.

#pragma once

#include "mxfp4_moe_aux_dispatch.h"

// Forward declarations of every codegen'd aux instance.
"""]
        for inst in instances:
            out.append(self._decl_extern_c(inst) + "\n")

        for fn_type, macro in self._MACRO.items():
            names = [i.name for i in instances if i.fn_type == fn_type]
            self._emit_map(out, macro, names)

        (self.working_path / "mxfp4_moe_aux_lookup.h").write_text("".join(out))

    def run(self):
        self.working_path.mkdir(parents=True, exist_ok=True)
        insts = list(self.enumerate_instances())
        self.gen_instances(insts)
        self.gen_lookup(insts)
        print(
            f"mxfp4_moe aux codegen: {len(insts)} instances under "
            f"{self.working_path}/instances/"
        )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--working_path",
        required=True,
        help="output dir for generated instances + lookup header",
    )
    args = ap.parse_args()
    mxfp4_moe_aux_codegen(args.working_path).run()


if __name__ == "__main__":
    main()
